language: php

dist: trusty
sudo: false

php:
  - 7.3.5

notifications:
  slack:
    rooms:
      - secure: QueECnL8Q0WfmGL0S/0RUfF040pQ0ag2AGlD/csjW6F20DkmE+V2vgYQix7MvcMtIKpK5RzdJraZPTxOBBCR1RSGdgt4L42ULfLJijlQnLaXYZF8P7dR2+Lcu11li5bOA8eM1NoqKfhF7O6DBqoMQHgWV/UqGA3RVWe35A37sfkmHN4Jr5fU5xZBlgqoRncqFMFWOtVo3NrMqCHMoUU/ailQttPJtIdfk5lqn6/JuWaHJh6yo371ujEFEpi8giaiT4n/QdS7N3qTEbESX2Hr3DZ9PXxo6iB1BSxITYwyQO3ngWD/foQmjX6x/shb2NSnHCHK4IcIfbRlvy/NMA8JmEi5/7iWzCek/Oz75YYdwm+VdC39J14fvqDs6ytKutNlThSvR5H7JeYGSk/wV64KUkrz8Nkgqemh+Q2N8NAb30yjSBO/VnUihBeUkjyELSR1SJZC27QlEQuTPZUt6gfuT09pY0LnlwZ8lYjEBsjnnRHBxFxYLmXCj1rozqUhdHjX8JBW3wu1PF5iG2TX4DGSSdW/RoamIJB4syXK4pQXQ72W9I4NdogUt0n/0tYMNu8olV3sSMTQE0iGXVtFAhwvUcrsfVQZQ0Z4Qmjc7nZ8Jsf/nnEC90FOQxOGCfR1ckPkDibyCCaYpoKwD1u+wm9wWjVk5CzTSoa46EoYNtrwzzo=
      - secure: G+9WH7eZEOIz08K3jcLmZkq/iCpiZyUQEXCazqxg+LTzD0WOliFbn/TflsfN0W2unDpN679+2ebRUwAg8p/8lVJ+ARbNtC+nqIMWnjrLE6TQXJgvzHCcNBa8EvZ0+mt91mHDmaIm3ajD2rY11fN2x/ME5aI+BwRALjADEig/kr/Q3KQdqBmzZRcByr3E7GJ/tCjriVmF/46uRVU81puTS5xzHy4Y0jdZBG0+g6YKV4/yfKp6ud9tdOPfyC72PNmWxx6AFUql+z/aL52X/DgXUkn7byYEqdAEocnz7wYyas2nkpdKFH9wdFGXtpdIIXMUShx3UpJ/7jXtHp1FoMVWmvZQJGM/HixrHvYf4Q4Jr3k3Ayqm0yGRAj4LFT+DCKl+stzbYHFadRur8fi8gKjR6rCaZ4J4M49kXzfGuUXVELfRPv6iWgjae7aanjXT2rRVcD3zL4OcxxT+CJbXjKev27khOb/m3GAUx1f6ySFQQ3DvDzrMPRJo/M8O/WFsHw0BczFTJjro7ZqhbpR3Av8yetBQ9C3sG/fFscKBPAM9WtMTD6UJazu8YZyFGqO+cLjJec0/lIZx/n+IUjLtqeep90a6GyG9V5y8CpoFN8TInKqcXKsz18aoEqVDwDtGGvo8nJKYzyeEOxKdsZfQhaRJdLlxRgeQyNNSiebRBMBWZ1o=
    on_success: always
    on_failure: always
  webhooks:
    secure: "sr+Mld+wqnyNpX57YlOSjxrUf1E9OqDp60N1kGYYwZMMH8FgsLUC7clj2K8Sc/K5zmnIAomE2jQ9h0aPNHJi7E5aqgPSH0PMRvL9foNOm3YHJ9B7FrRRsSQnMLB4g4HhS92vZJ0k1SrIHLNSTMG/HLOMbnJJ2XUYVQGBo/yF2+cIsiLbykRqm/oEGjMg3SFAoWehBVFPECjFIdw4aSt/9q1lWJYYAyQ/DtrYB7LqkrIHiEsklPAUHnNyRfyybCEMdgV99eRQyc/3Y8kMPDsa1712vo4nZC9p2Y5q7C+ao1iQlSaqsAIyYXJHkhL1edlg/fpcS9wru2JeysU/SJyW0B/z/Cz+3HMcxsjJeyZhpISBckxnS997Jk3mmCtk+SJN+Wkxz0fwDH72Tug9GO/pSVUYlqc1y3oJwWE/k4rwcwz65Z9pm+/Fg2MT2buvvwqnkPTd6lOl4vjtZuIM/z9VQaiNPwcHJgKpipj8eC7tp92gWyYy/rSw4xbZ8lF+m6TD3qzTs59gw53Uim5gLm1tN4fP48jXSZJsK6Jpzau792N6vXdLIZGXjKzRQcCcYPQEYtzWy2IPJHCsJsjKnGvvw0ZKCv+r1C8rBFpK+aGC2phNR6TyXXxl0+lWKhEe4mPRd8aJmAdwGFwlCRIKQEm34+bX/cNxlZguyURgnwKeB6I="


addons:
  chrome: stable
  mariadb: '10.3'
  #sauce_connect: true

env:
  global:
    - SAUCE_USERNAME=abhayagiri
    - secure: "f12gM5QmnPOeCwFhZgAejs9Q8gGlW3/api21lFCkCB8r2FkG6dMoneR0/iUUOlfrs6M2Sdd4MKjM01ZsFIg/oburrNVB5fKf0DL6CdMX4JHVqdJY1+OuS4S8fSyrZXWejDRmoWwPqrKAChx8932GJKlFE6mxSQtc3DnluSGszBBOqVrc52rsZlC7nTOLhhEMKiNIyLxOkyJKt22HT+TGYs33FlrxfLvf+B85Mkk0EcztBTIipHfiAY/s+95OYiZJ0SUs774RAvSERILii5BLTB0UGyPWDVPSMYPIN3PCzgzGSR3HsL/zxnsWRvBYuHWPzkGqEi5Rp+3c93JxyTdIHM1QkWRtLgQS2hOES3k9EfVW4/e26/Ks0mQmtLEv7B3ZTF301tNz1wZ4uusYlLrpwgusIdCB5+bzC8KtFzzwOH75kq5WCq3gGXgrpb0KuaW2lt4lMcUrbYGLKQsLZEjAHXO0eVUgwaiq6iW2Gelc75gURIGJPnv0hAbch3kFY1iia9uhLe+sys6zWDjNX/gTOaOJzOCfX5BNOIeoUMqH0JLLFrKDKKC9nJfN7Fl5+VjUk/DmFnd/DzXy7WSznMPmREmLrizWbRMeWd7sQcUne3XYLgCRbcOcqz/QKFbgr+Qf3LIQ6yeeKcvoL7FlunzCZVjAxtYUbsZUHDwMrsz18kk="

mysql:
  database: abhayagiri
  username: root
  encoding: utf8

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis/php.ini
  - mysql --version
  - php --version
  - composer --version
  - google-chrome-stable --version

install:
  # Install nvm, Node and npm
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install 12.4.0
  - npm update -g --verbose
  - node --version
  - npm --version
  # This must come before composer install otherwise Laravel Dusk will panic
  - cp .env.example .env
  # Install PHP dependencies
  - composer install
  # Install Chrome driver for Laravel Dusk
  - php artisan dusk:chrome-driver
  - vendor/laravel/dusk/bin/chromedriver-linux --version
  # Install database and media files
  - mysql -u root -e "CREATE DATABASE abhayagiri;"
  - mysql -u root -e "CREATE USER 'abhayagiri'@'localhost' IDENTIFIED BY 'abhayagiri';"
  - mysql -u root -e "GRANT ALL ON abhayagiri.* TO 'abhayagiri'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - echo "DB::select('SELECT @@session.sql_mode')" | php artisan tinker
  - php artisan app:import-database
  - php artisan app:import-media
  # Install Javascript dependencies and build front-end
  - npm install
  - npm run build
  # Build Laravel Mix Vue assets
  - ( cd mix && npm install && npm run production )
  # Setup any last bits...
  - php artisan app:fix-local-dirs
  - php artisan key:generate
  - php artisan app:stamp

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000/ > /dev/null 2>&1 &
  - php artisan serve > /dev/null 2>&1 &

script:
  - php artisan test

after_script:
  - curl http://localhost:8000/
  - cat "error.log" || true
  - killall php
  - killall chrome

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - node_modules
    - storage/tmp
    - vendor
