language: php

dist: bionic

notifications:
  slack:
    rooms:
      - secure: G+9WH7eZEOIz08K3jcLmZkq/iCpiZyUQEXCazqxg+LTzD0WOliFbn/TflsfN0W2unDpN679+2ebRUwAg8p/8lVJ+ARbNtC+nqIMWnjrLE6TQXJgvzHCcNBa8EvZ0+mt91mHDmaIm3ajD2rY11fN2x/ME5aI+BwRALjADEig/kr/Q3KQdqBmzZRcByr3E7GJ/tCjriVmF/46uRVU81puTS5xzHy4Y0jdZBG0+g6YKV4/yfKp6ud9tdOPfyC72PNmWxx6AFUql+z/aL52X/DgXUkn7byYEqdAEocnz7wYyas2nkpdKFH9wdFGXtpdIIXMUShx3UpJ/7jXtHp1FoMVWmvZQJGM/HixrHvYf4Q4Jr3k3Ayqm0yGRAj4LFT+DCKl+stzbYHFadRur8fi8gKjR6rCaZ4J4M49kXzfGuUXVELfRPv6iWgjae7aanjXT2rRVcD3zL4OcxxT+CJbXjKev27khOb/m3GAUx1f6ySFQQ3DvDzrMPRJo/M8O/WFsHw0BczFTJjro7ZqhbpR3Av8yetBQ9C3sG/fFscKBPAM9WtMTD6UJazu8YZyFGqO+cLjJec0/lIZx/n+IUjLtqeep90a6GyG9V5y8CpoFN8TInKqcXKsz18aoEqVDwDtGGvo8nJKYzyeEOxKdsZfQhaRJdLlxRgeQyNNSiebRBMBWZ1o=
    on_success: always
    on_failure: always
  webhooks:
    secure: "sr+Mld+wqnyNpX57YlOSjxrUf1E9OqDp60N1kGYYwZMMH8FgsLUC7clj2K8Sc/K5zmnIAomE2jQ9h0aPNHJi7E5aqgPSH0PMRvL9foNOm3YHJ9B7FrRRsSQnMLB4g4HhS92vZJ0k1SrIHLNSTMG/HLOMbnJJ2XUYVQGBo/yF2+cIsiLbykRqm/oEGjMg3SFAoWehBVFPECjFIdw4aSt/9q1lWJYYAyQ/DtrYB7LqkrIHiEsklPAUHnNyRfyybCEMdgV99eRQyc/3Y8kMPDsa1712vo4nZC9p2Y5q7C+ao1iQlSaqsAIyYXJHkhL1edlg/fpcS9wru2JeysU/SJyW0B/z/Cz+3HMcxsjJeyZhpISBckxnS997Jk3mmCtk+SJN+Wkxz0fwDH72Tug9GO/pSVUYlqc1y3oJwWE/k4rwcwz65Z9pm+/Fg2MT2buvvwqnkPTd6lOl4vjtZuIM/z9VQaiNPwcHJgKpipj8eC7tp92gWyYy/rSw4xbZ8lF+m6TD3qzTs59gw53Uim5gLm1tN4fP48jXSZJsK6Jpzau792N6vXdLIZGXjKzRQcCcYPQEYtzWy2IPJHCsJsjKnGvvw0ZKCv+r1C8rBFpK+aGC2phNR6TyXXxl0+lWKhEe4mPRd8aJmAdwGFwlCRIKQEm34+bX/cNxlZguyURgnwKeB6I="

services:
  - mysql

addons:
  - chrome: stable

php:
  - 7.3.12

mysql:
  database: abhayagiri
  username: root
  encoding: utf8mb4

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini

install:
  # Install latest npm
  - npm update -g --verbose
  # Create database and user for dusk
  - mysql -u root -e "CREATE DATABASE abhayagiri_dusk CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  - mysql -u root -e "CREATE USER 'abhayagiri_dusk'@'localhost' IDENTIFIED BY 'abhayagiri_dusk';"
  - mysql -u root -e "GRANT ALL ON abhayagiri_dusk.* TO 'abhayagiri_dusk'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  # Setup and install dependencies
  - scripts/install-local.sh
  # Setup any last bits...
  - php artisan route:cache
  - php artisan app:fix-local-dirs
  - php artisan app:stamp

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000/ > /dev/null 2>&1 &
  - php artisan serve --port=8001 --env=dusk.local > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit --testdox
  - php artisan dusk --env=dusk.local --testdox
  - npm test

after_script:
  - curl http://localhost:8000/
  - cat "error.log" || true
  - killall php
  - killall chrome
  # Output version information
  - php --version
  - mysql --version
  - mysql -u root -e "SELECT @@session.sql_mode;"
  - composer --version
  - google-chrome-stable --version
  - node --version
  - npm --version

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - mix/node_modules
    - node_modules
    - storage/tmp
    - vendor
