language: php

dist: bionic

notifications:
  slack:
    rooms:
      - secure: G+9WH7eZEOIz08K3jcLmZkq/iCpiZyUQEXCazqxg+LTzD0WOliFbn/TflsfN0W2unDpN679+2ebRUwAg8p/8lVJ+ARbNtC+nqIMWnjrLE6TQXJgvzHCcNBa8EvZ0+mt91mHDmaIm3ajD2rY11fN2x/ME5aI+BwRALjADEig/kr/Q3KQdqBmzZRcByr3E7GJ/tCjriVmF/46uRVU81puTS5xzHy4Y0jdZBG0+g6YKV4/yfKp6ud9tdOPfyC72PNmWxx6AFUql+z/aL52X/DgXUkn7byYEqdAEocnz7wYyas2nkpdKFH9wdFGXtpdIIXMUShx3UpJ/7jXtHp1FoMVWmvZQJGM/HixrHvYf4Q4Jr3k3Ayqm0yGRAj4LFT+DCKl+stzbYHFadRur8fi8gKjR6rCaZ4J4M49kXzfGuUXVELfRPv6iWgjae7aanjXT2rRVcD3zL4OcxxT+CJbXjKev27khOb/m3GAUx1f6ySFQQ3DvDzrMPRJo/M8O/WFsHw0BczFTJjro7ZqhbpR3Av8yetBQ9C3sG/fFscKBPAM9WtMTD6UJazu8YZyFGqO+cLjJec0/lIZx/n+IUjLtqeep90a6GyG9V5y8CpoFN8TInKqcXKsz18aoEqVDwDtGGvo8nJKYzyeEOxKdsZfQhaRJdLlxRgeQyNNSiebRBMBWZ1o=
    on_success: always
    on_failure: always
  webhooks:
    secure: "sr+Mld+wqnyNpX57YlOSjxrUf1E9OqDp60N1kGYYwZMMH8FgsLUC7clj2K8Sc/K5zmnIAomE2jQ9h0aPNHJi7E5aqgPSH0PMRvL9foNOm3YHJ9B7FrRRsSQnMLB4g4HhS92vZJ0k1SrIHLNSTMG/HLOMbnJJ2XUYVQGBo/yF2+cIsiLbykRqm/oEGjMg3SFAoWehBVFPECjFIdw4aSt/9q1lWJYYAyQ/DtrYB7LqkrIHiEsklPAUHnNyRfyybCEMdgV99eRQyc/3Y8kMPDsa1712vo4nZC9p2Y5q7C+ao1iQlSaqsAIyYXJHkhL1edlg/fpcS9wru2JeysU/SJyW0B/z/Cz+3HMcxsjJeyZhpISBckxnS997Jk3mmCtk+SJN+Wkxz0fwDH72Tug9GO/pSVUYlqc1y3oJwWE/k4rwcwz65Z9pm+/Fg2MT2buvvwqnkPTd6lOl4vjtZuIM/z9VQaiNPwcHJgKpipj8eC7tp92gWyYy/rSw4xbZ8lF+m6TD3qzTs59gw53Uim5gLm1tN4fP48jXSZJsK6Jpzau792N6vXdLIZGXjKzRQcCcYPQEYtzWy2IPJHCsJsjKnGvvw0ZKCv+r1C8rBFpK+aGC2phNR6TyXXxl0+lWKhEe4mPRd8aJmAdwGFwlCRIKQEm34+bX/cNxlZguyURgnwKeB6I="

services:
  - mysql

addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

php:
  - 7.3.12

env:
  # CYPRESS_RECORD_KEY
  secure: "0r053dwcDu0T0lv2T5OEMhMRbBkJWm7Nq4ejX3C45sIS4Md+avozxqb2QbjFDHUpNUOniClUZji5Meo27nGpS7BkFIPN2Uww1sZebKiZ3PjmtCKAvtEbMaLsiTkqVh3Cp8GeKFw25O95UjFGljbGjjmo26yNyyVhZkuCAcVToKDaTur11bc8QNx9fQIhBCp1IYjyqZ0LQm/MlXFKH/cct7z6M0LuODjsbCUkk2Xnf7oqUYIOltpCN+zlCAhEzoLqeRKtfbTY4qrj5Ot48OOIgsBFbb6kMmroqp28RpcpaBUP9rd6X4DcQtoYzUiDA5M1koSpu6f/pHl/dyvPP3fiJHEC6RrsqmWDVdjSkvbehwlhgJSmfTF1fyXZcJqoMxNOxaw9gsMaPNTq//yPU3bUgB5+dttFG2f/9W4L8pvoiR5MmAHdZ2SYBB8xN2GDQwEphnKkJQ/PtRKMhWNag7sI/2d/6XKW89z7B0AWPQ11Kc0Qp3Q6sWMQTMGDI/rrZiTD8bUXAUFdFEKedP7idlpa3S74+FD76ye5LKWT+LToDATpphfV1D8by1Pa0JWccW1xdI1Fwck6NNujHuIW2DZ791usOXzmV0qiT8BjCAmDO8eMfcLcpos79Ofh+gUH25N5RHA5c1LQGY5fOcILaOThuc3EhhiAjlhAd2yW9eM8J2A="

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini

install:
  # Install latest npm
  - npm update -g --verbose
  # Setup databases
  - scripts/local/setup-databases.sh
  # Setup and install dependencies
  - scripts/install-local.sh
  # Setup any last bits...
  - php artisan route:cache
  - php artisan app:stamp

before_script:
  - APP_ENV=test php artisan serve --port=8001 > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit --testdox
  - APP_ENV=test php artisan migrate:fresh --seed
  - $(npm bin)/cypress run --record

after_script:
  - cat "error.log" || true
  - killall php
  # Output version information
  - php --version
  - mysql --version
  - mysql -u root -e "SELECT @@session.sql_mode;"
  - composer --version
  - google-chrome-stable --version
  - node --version
  - npm --version

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache
    - $HOME/.npm
    - node_modules
    - storage/tmp
    - vendor
