language: php

sudo: required

php:
  - 7.0

addons:
  sauce_connect: true

env:
  global:
    - SAUCE_USERNAME=abhayagiri
    - secure: "Wnuv6NLPTxWmWzd9BzKqEsqVrf70uS8o2WusTOiIPNOgcGf5Pq1nKqdeflKVLXefJSS4yJeJnCven6A5IhkUsVvyysk/HvjjocEEkrqQibYP9e06+yJ0uNtXMfg1cA5s/YM1M1mrCED/WZ+AW0u37CD7Ch6KaBbDUVmwwGyCSN8LDLvqvtLbJDcByrjy7cHtrOCqIF21tUBNxfpyhgA/cyKSayZO+bBAXqM0AbTFS2tA23B2ronkOrgNKGERmWeOI6trmVVrsnkSY02FaDIKuPkRN9DnADVQ8N01ZS2DFvf7EqGb27Q+ZgR1C33X3rDaCNXcBFgyao9wfrXEJhBb2AfT63MZ2qEqbsVxHZCvx0Yj8/DjyQlJfsJ23ER29rsm2HhJj2S2ekdj09Vv0WnVHczZBQSJCzvKRh4aTFZtd4j2n89a+C86HUJ6wRaIPSfHkv4dtiWOuyYjXzjLGr/mb5dDzkbMLLBacdOy9g7gIIgXF1Z9vmZ2VEgRunU605m676vkBCD2In2J+gcV5y12Y1ICEsUOl1uDb3tuBFYKcN9EmU/ulaTn9gtgCvnZdoNOLZCbyHzU7H7O1DXyZQBU6WFR6Yg86/Y9d9EQqROoazNz50Ik5cIZI3/zsnkIf9k+y0h2Z83NY1UAexjG1Zp27T+Ma4ifXMmYmPsh4F3ppYA="

services:
  - mysql

mysql:
  database: abhayagiri
  username: root
  encoding: utf8

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis/php.ini
  - sudo apt-get update > /dev/null

install:
  # install required packages
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi
  # enable php-fpm
  # add fix from https://github.com/formapro/JsFormValidatorBundle
  - sudo cp -v ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo cp -v ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ls -R ~/.phpenv/versions/$(phpenv version-name)/etc/
  - sudo a2enmod rewrite headers actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f travis/apache.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # setup database and user
  - mysql -u root -e "CREATE DATABASE abhayagiri;"
  - mysql -u root -e "CREATE USER 'abhayagiri'@'localhost' IDENTIFIED BY 'abhayagiri';"
  - mysql -u root -e "GRANT ALL ON abhayagiri.* TO 'abhayagiri'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  # configure, composer install, install database and media files
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan command:import-media
  - php artisan command:import-database
  - php artisan command:fix-local-dirs
  - npm install
  - npm run build
  - node tests/selenium-setup.js

before_script:
  - php artisan serve &

script:
  - composer exec -- codecept run -vvv --debug
  - npm run test-saucelabs

after_script:
  - cat "error.log"
  - curl http://localhost/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  slack:
    secure: QueECnL8Q0WfmGL0S/0RUfF040pQ0ag2AGlD/csjW6F20DkmE+V2vgYQix7MvcMtIKpK5RzdJraZPTxOBBCR1RSGdgt4L42ULfLJijlQnLaXYZF8P7dR2+Lcu11li5bOA8eM1NoqKfhF7O6DBqoMQHgWV/UqGA3RVWe35A37sfkmHN4Jr5fU5xZBlgqoRncqFMFWOtVo3NrMqCHMoUU/ailQttPJtIdfk5lqn6/JuWaHJh6yo371ujEFEpi8giaiT4n/QdS7N3qTEbESX2Hr3DZ9PXxo6iB1BSxITYwyQO3ngWD/foQmjX6x/shb2NSnHCHK4IcIfbRlvy/NMA8JmEi5/7iWzCek/Oz75YYdwm+VdC39J14fvqDs6ytKutNlThSvR5H7JeYGSk/wV64KUkrz8Nkgqemh+Q2N8NAb30yjSBO/VnUihBeUkjyELSR1SJZC27QlEQuTPZUt6gfuT09pY0LnlwZ8lYjEBsjnnRHBxFxYLmXCj1rozqUhdHjX8JBW3wu1PF5iG2TX4DGSSdW/RoamIJB4syXK4pQXQ72W9I4NdogUt0n/0tYMNu8olV3sSMTQE0iGXVtFAhwvUcrsfVQZQ0Z4Qmjc7nZ8Jsf/nnEC90FOQxOGCfR1ckPkDibyCCaYpoKwD1u+wm9wWjVk5CzTSoa46EoYNtrwzzo=
