version: '2'
services:
  cli:
    image: abhayagiri/php-5.6-apache
    command: [ "true" ]
    volumes:
      - .:/app
    working_dir: /app
    links:
      - web
      - db
  web:
    image: abhayagiri/php-5.6-apache
    command: [-r, apache2ctl, -D, FOREGROUND]
    ports:
      - 80:80
    volumes:
      - ..:/app
    working_dir: /app
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password1
      - MYSQL_DATABASE=abhayagiri
      - MYSQL_USER=abhayagiri
      - MYSQL_PASSWORD=abhayagiri
    volumes:
      - abhayagiri-db:/var/lib/mysql
volumes:
  abhayagiri-db:
