#!/usr/bin/env php
<?php

chdir(__DIR__);

if (!file_exists('.env')) {
    $generateKey = true;
    copy('.env.example', '.env');
} else {
    $generateKey = false;
}

system('composer install');

if ($generateKey) {
    system('php artisan key:generate');
}

system('php artisan app:import-media');
system('php artisan app:import-database');

system('npm install');
system('cd mix && npm install');
