#!/usr/bin/env php
<?php

chdir(__DIR__);

if (!file_exists('.env')) {
    $generateKey = true;
    copy('.env.example', '.env');
} else {
    $generateKey = false;
}

system('composer install');

if ($generateKey) {
    system('php artisan key:generate');
}

// TODO: Create Database

system('php artisan command:import-media');
system('php artisan command:import-database');
system('php artisan command:fix-local-dirs');
