version: '2'
services:
  web:
    build: ./web
    command: [apache2-foreground]
    ports:
      - 80:80
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password1
      - MYSQL_DATABASE=abhayagiri
      - MYSQL_USER=abhayagiri
      - MYSQL_PASSWORD=abhayagiri
    volumes:
      - abhayagiri-db-volume:/var/lib/mysql
volumes:
  abhayagiri-db-volume:
