version: '2'
services:
  web:
    extends:
      file: docker/common.yml
      service: web
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_USER=app
      - APP_UID=1000
      - APP_GROUP=staff
      - APP_GID=50
  db:
    extends:
      file: docker/common.yml
      service: db
volumes:
  abhayagiri-db-volume:
