#!/bin/bash

# Based on https://github.com/kojiromike/docker-magento/blob/master/apache/start_safe_perms

##
# Detect the ownership of the webroot and create a user and permissions accordingly
#
main() {
    local owner group owner_id group_id tmp
    read owner group owner_id group_id < <(stat -c '%U %G %u %g' .)
    if [[ $owner = UNKNOWN ]]; then
        owner=app
        if [[ $group = UNKNOWN ]]; then
            group=$owner
            addgroup --system --gid "$group_id" "$group"
        fi
        adduser --home "/app" --system --uid=$owner_id --gid=$group_id "$owner"
    fi
    tmp=/tmp/$RANDOM
    {
        echo "User $owner"
        echo "Group $group"
        grep -v '^User' /etc/apache2/apache2.conf |
            grep -v '^Group'
    } >> "$tmp" &&
    cat "$tmp" > /etc/apache2/apache2.conf &&
    rm "$tmp"
    # Not volumes, so need to be chowned
    chown -R "$owner:$group" /var/{lock,log,run}/apache*
    if [ "$1" = "-r" ]; then
        shift
        exec "$@"
    else
        sudo -u $owner -H "$@"
    fi
}

main "$@"
